### PR TITLE
Header for Landing Page

### PR DESCRIPTION
**Pull request by rashmiagar**

### CODE REVIEW

**Comment by dimitriost1** [comment]
We can remove MUI library and possibly use daisyUI library.

**Comment by rashmia1985** [comment]
> We can remove MUI library and possibly use daisyUI library.

This is done. @dimitriost1 Can you please review and merge?

**Comment by dimitriost1** [comment]
do we really need search field?

**Review by JustDaile — CHANGES_REQUESTED** [review]
Please fix signup button issues as detailed in discord.

**Review by JustDaile — COMMENTED** [review]
You've added react router without any setup.

**Review by JustDaile — CHANGES_REQUESTED** [review]
Perhaps update the router to use routes
```jsx
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
      <Router>
        <Routes>
          <Route path='/' element={<App />} />
        </Routes>
      </Router>
  </React.StrictMode>,
)
```

**Review by JustDaile — APPROVED** [review]

**Pull request merged**
